language: cpp

#os:
#  - linux
#  - osx

branches:
  only:
    - master
    - travis_osx

env:
  global:
    - RENDERDOC_TRAVIS_BUILD=1 RENDERDOC_CI_BUILD=1

# only build docs once on linux
matrix:
  fast_finish: true
  include:
    - os: linux
      dist: trusty
      sudo: required
      env: CODE_BUILD=1 LINUX_BUILD=1 APPLE_BUILD=0 DOCS_BUILD=0
      compiler: gcc
    - os: linux
      dist: trusty
      sudo: required
      env: CODE_BUILD=1 LINUX_BUILD=1 APPLE_BUILD=0 DOCS_BUILD=0
      compiler: clang
    - os: linux
      dist: trusty
      sudo: required
      compiler: gcc
      env: CODE_BUILD=0 LINUX_BUILD=0 APPLE_BUILD=0 DOCS_BUILD=1
    - os: osx
      osx_image: xcode8.2
      env: CODE_BUILD=1 LINUX_BUILD=0 APPLE_BUILD=1 DOCS_BUILD=0
      compiler: clang

# install dependencies
install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo add-apt-repository -y 'ppa:ubuntu-toolchain-r/test' ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo add-apt-repository -y 'ppa:beineri/opt-qt562-trusty' ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo add-apt-repository -y 'deb http://apt.llvm.org/precise/ llvm-toolchain-precise-3.8 main' ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then wget -O - http://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add - ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update -qq ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]] && [[ "$CODE_BUILD" == "1" ]]; then sudo apt-get install --allow-unauthenticated -y -qq libx11-dev mesa-common-dev libgl1-mesa-dev qt56base qt56x11extras libxcb-keysyms1-dev gdb clang-format-3.8 ; fi
  - if [[ "$DOCS_BUILD" == "1" ]]; then sudo pip install --upgrade pip setuptools ; sudo pip install Sphinx sphinx-rtd-theme ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]] && [[ "$CODE_BUILD" == "1" ]]; then clang-format-3.8 -i -style=file $(find pdblocate/ qrenderdoc/ renderdoc/ renderdoccmd/ renderdocshim/ -type f -regex '.*\(/3rdparty/\|/official/\|resource.h\).*' -prune -o -regex '.*\.\(c\|cpp\|h\)$' -print) ; fi
  - git clean -f
  - git diff --exit-code

script:
  - sh ./scripts/hash_version.sh
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]] && [[ "$CODE_BUILD" == "1" ]]; then . /opt/qt56/bin/qt56-env.sh ; fi
  - if [[ "$CODE_BUILD" == "1" ]]; then mkdir build && cd build && cmake -DCMAKE_BUILD_TYPE=Debug .. && make ; fi
#  - if [[ "$DOCS_BUILD" == "1" ]]; then cd docs/ && make html ; fi
